# This workflow will build a .NET project and run Snyk to check for vulnerabilities

name: DevSecOps With Snyk

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build/Test and Security Check
    runs-on: ubuntu-latest

    steps:
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Dotnet restore
      run: dotnet restore

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/dotnet@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Dotnet build
      run: dotnet build --configuration Release --no-restore

    - name: Dotnet format
      run: dotnet format --verbosity detailed --verify-no-changes 

    - name: Dotnet test
      run: dotnet test --configuration Release --no-build --verbosity detailed
    